// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EthoUber_Ios
{
	public partial class NewViewController : UIView
	{
		public NewViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
